#!/usr/bin/env bash
# This script installs Nginx web server and configures it.

# Install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
