#!/usr/bin/env bash
#This script will make the  Nginx server to listen on port 80

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#restarts the nginx server
service nginx restart
